language: rust
os:
  - windows
  - osx
  - linux
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
  fast_finish: true
cache: cargo

script:
  - cargo test
  - cargo bench
