[package]
name = "cuid"
version = "0.1.0"
authors = ["Matthew Planchard <msplanchard@gmail.com>"]

[dev-dependencies]
criterion = "~0.2"

[dependencies]
rand = "~0.6"
hostname = "~0.1"

[[bench]]
name = "cuid"
harness = false
