[package]
name = "cuid"
version = "0.1.0"
license = "MIT"
authors = ["Matthew Planchard <msplanchard@gmail.com>"]
description = "An implementation of CUID protocol in rust"

[dev-dependencies]
criterion = "0.3"

[dependencies]
hostname = "~0.1"
lazy_static = "1.4"
parking_lot = "0.10.0"
rand = "0.7.3"

[[bench]]
name = "cuid"
harness = false
