[package]
name = "cuid"
version = "0.1.0"
authors = ["Matthew Planchard <msplanchard@gmail.com>"]

[dev-dependencies]
criterion = "~0.2"

[dependencies]
hostname = "~0.1"
lazy_static = "~1.2"
rand = "~0.6"

[[bench]]
name = "cuid"
harness = false
