[package]
name = "cuid"
version = "0.1.0"
license = "MIT"
authors = ["Matthew Planchard <msplanchard@gmail.com>"]
description = "An ipmlementation of CUID protocol in rust"

[dev-dependencies]
criterion = "~0.2"

[dependencies]
hostname = "~0.1"
lazy_static = "1.4"
rand = "~0.6"
parking_lot = "0.7"

[[bench]]
name = "cuid"
harness = false
